In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("bank.csv")

In [4]:
df.head()

,Bank_Name,Card_Name,Annual_Fee,"Grocery_Cashback(%) [Zepto, BigBasket, etc.]",Travel_Cashback(%),"Dining_Cashback [Swiggy, Zomato, etc.](%)",Min_Income_Required(Yearly),Limit(montly),Grocery Discount,Travel_Discount,Dining_Discount,Rewards Points,Review InPoints(out of 5),CardType,Lounge access per year,Total Cashback(%)
0,ICICI,platinum ship credit card,0,1.5,2.0,15.0,300000,60000,1,8,15,0.02,4.5,credit,0.0,18.5
1,ICICI,Amazon pay icici card,0,3.0,5.0,3.0,300000,100000,3,5,10,0.00,4.0,credit,0.0,11.0
2,ICICI,Coral Credit Card,500,5.0,10.0,20.0,500000,80000,5,10,20,0.02,4.0,credit,2.0,35.0
3,IDFC,Millennia,0,1.0,0.0,0.0,300000,125000,0,0,0,150.00,1.5,credit,5.0,1.0
4,IDFC,First Classic,0,0.0,0.0,0.0,500000,150000,0,0,0,3.00,2.5,credit,6.0,0.0

In [5]:
df.describe()

,Annual_Fee,"Grocery_Cashback(%) [Zepto, BigBasket, etc.]",Travel_Cashback(%),"Dining_Cashback [Swiggy, Zomato, etc.](%)",Grocery Discount,Travel_Discount,Dining_Discount,Rewards Points,Review InPoints(out of 5),Lounge access per year,Total Cashback(%)
count,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,68.000000,68.000000,78.000000
mean,794.064103,1.621795,2.576923,3.121795,1.987179,2.730769,5.807692,13.249547,6.651471,2.867647,7.320513
std,1951.845163,2.339922,3.767666,4.943306,3.213177,3.681026,6.654864,38.970825,16.262855,3.036614,8.117631
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020000,3.500000,0.000000,1.000000
50%,325.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.000000,1.000000,4.000000,2.000000,5.000000
75%,500.000000,2.000000,4.750000,4.750000,3.000000,5.000000,10.000000,3.000000,4.200000,4.000000,11.000000
max,12500.000000,10.000000,15.000000,25.000000,10.000000,10.000000,25.000000,200.000000,99.000000,14.000000,35.000000

In [6]:
df.columns

Index(['Bank_Name', 'Card_Name', 'Annual_Fee',
       'Grocery_Cashback(%) [Zepto, BigBasket, etc.]', 'Travel_Cashback(%)',
       'Dining_Cashback [Swiggy, Zomato, etc.](%)',
       'Min_Income_Required(Yearly)', 'Limit(montly)', 'Grocery Discount',
       'Travel_Discount', 'Dining_Discount', 'Rewards Points',
       'Review InPoints(out of 5)', 'CardType', 'Lounge access per year',
       'Total Cashback(%)'],
      dtype='object')

In [8]:
df.loc[0]

Bank_Name                                                           ICICI
Card_Name                                       platinum ship credit card
Annual_Fee                                                              0
Grocery_Cashback(%) [Zepto, BigBasket, etc.]                          1.5
Travel_Cashback(%)                                                    2.0
Dining_Cashback [Swiggy, Zomato, etc.](%)                            15.0
Min_Income_Required(Yearly)                                        300000
Limit(montly)                                                       60000
Grocery Discount                                                        1
Travel_Discount                                                         8
Dining_Discount                                                        15
Rewards Points                                                       0.02
Review InPoints(out of 5)                                             4.5
CardType                                                           credit
Lounge access per year                                                0.0
Total Cashback(%)                                                    18.5
Name: 0, dtype: object

In [9]:
df.sort_values("Grocery_Cashback(%) [Zepto, BigBasket, etc.]", ascending=False)

,Bank_Name,Card_Name,Annual_Fee,"Grocery_Cashback(%) [Zepto, BigBasket, etc.]",Travel_Cashback(%),"Dining_Cashback [Swiggy, Zomato, etc.](%)",Min_Income_Required(Yearly),Limit(montly),Grocery Discount,Travel_Discount,Dining_Discount,Rewards Points,Review InPoints(out of 5),CardType,Lounge access per year,Total Cashback(%)
27,Bank of Baroda,IRCTC Credit Card,500,10.0,15.0,0.0,480000,100000,0,0,0,2.00,4.0,Credit,4.0,25.0
28,Bank of Baroda,Prime Credit Card,0,10.0,15.0,0.0,15000,100000,0,0,0,2.00,4.0,Credit,0.0,25.0
26,Bank of Baroda,HPCL Credit Card,499,10.0,15.0,0.0,480000,100000,0,0,0,2.00,4.0,Credit,4.0,25.0
44,Axis Bank,Axis Bank Value+ Debit Card,0,5.0,0.0,0.0,0,0,5,0,10,0.00,3.8,Debit,0.0,5.0
2,ICICI,Coral Credit Card,500,5.0,10.0,20.0,500000,80000,5,10,20,0.02,4.0,credit,2.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,Axis Bank,Axis Bank MyZone Credit Card,500,0.0,1.0,0.0,300000,50000,0,0,20,1.00,4.1,credit,4.0,1.0
43,Axis Bank,Axis Bank Delight Debit Card,0,0.0,0.0,25.0,0,0,0,0,25,0.00,4.0,Debit,4.0,25.0
45,Axis Bank,Axis Bank Titanium Rewards Debit Card,0,0.0,0.0,10.0,0,0,0,0,10,1.00,3.9,Debit,0.0,10.0
46,Axis Bank,Axis Bank Platinum Debit Card,0,0.0,0.0,5.0,0,0,0,0,5,1.00,3.8,Debit,0.0,5.0
77,Kotak Mahindra Bank,Kotak UPI RuPay Credit Card,0,0.0,0.0,0.0,250000,300000,0,0,0,3.00,3.9,Credit,0.0,0.0

In [10]:
df.sort_values("Dining_Cashback [Swiggy, Zomato, etc.](%)", ascending=False)

,Bank_Name,Card_Name,Annual_Fee,"Grocery_Cashback(%) [Zepto, BigBasket, etc.]",Travel_Cashback(%),"Dining_Cashback [Swiggy, Zomato, etc.](%)",Min_Income_Required(Yearly),Limit(montly),Grocery Discount,Travel_Discount,Dining_Discount,Rewards Points,Review InPoints(out of 5),CardType,Lounge access per year,Total Cashback(%)
43,Axis Bank,Axis Bank Delight Debit Card,0,0.0,0.0,25.0,0,0,0,0,25,0.00,4.0,Debit,4.0,25.0
2,ICICI,Coral Credit Card,500,5.0,10.0,20.0,500000,80000,5,10,20,0.02,4.0,credit,2.0,35.0
0,ICICI,platinum ship credit card,0,1.5,2.0,15.0,300000,60000,1,8,15,0.02,4.5,credit,0.0,18.5
15,IDBI,IDBI Delight Credit Card,500,5.0,10.0,15.0,240000,60000,5,10,15,1.00,3.5,credit,0.0,30.0
16,IDBI,Royale Signature card,2500,1.0,5.0,15.0,900000,300000,1,5,15,2.00,4.0,credit,4.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,Bank of Baroda,HPCL Credit Card,499,10.0,15.0,0.0,480000,100000,0,0,0,2.00,4.0,Credit,4.0,25.0
27,Bank of Baroda,IRCTC Credit Card,500,10.0,15.0,0.0,480000,100000,0,0,0,2.00,4.0,Credit,4.0,25.0
28,Bank of Baroda,Prime Credit Card,0,10.0,15.0,0.0,15000,100000,0,0,0,2.00,4.0,Credit,0.0,25.0
42,Axis Bank,Axis Bank MyZone Credit Card,500,0.0,1.0,0.0,300000,50000,0,0,20,1.00,4.1,credit,4.0,1.0
77,Kotak Mahindra Bank,Kotak UPI RuPay Credit Card,0,0.0,0.0,0.0,250000,300000,0,0,0,3.00,3.9,Credit,0.0,0.0