In [1]:
import pandas as pd

In [2]:
bank_df=pd.read_csv("bank.csv")
customer_df=pd.read_csv("customer_expense.csv")

In [3]:
max_gro=bank_df["Grocery_Cashback"].max()
best_grocery=bank_df[bank_df["Grocery_Cashback"]==max_gro][["Bank_Name","Card_Name","Grocery_Cashback"]]
best_grocery

         Bank_Name          Card_Name  Grocery_Cashback
26  Bank of Baroda   HPCL Credit Card              10.0
27  Bank of Baroda  IRCTC Credit Card              10.0
28  Bank of Baroda  Prime Credit Card              10.0

In [5]:
no_annual = bank_df[bank_df["Annual_Fee"] == 0][["Bank_Name","Card_Name","Annual_Fee"]]
no_annual

              Bank_Name                              Card_Name  Annual_Fee
0                 ICICI              platinum ship credit card           0
1                 ICICI                  Amazon pay icici card           0
3                  IDFC                              Millennia           0
4                  IDFC                          First Classic           0
6                  IDFC                           First Select           0
8                  IDFC                           Republic Day           0
11                  PNB                         Global Classic           0
13                  PNB                        Patanjali RuPay           0
28       Bank of Baroda                      Prime Credit Card           0
29          Canara Bank               VISA Classic Credit Card           0
30          Canara Bank                    MasterCard Standard           0
31          Canara Bank             RuPay Platinum Credit Card           0
33          Canara Bank                       RuPay Debit Card           0
34          Canara Bank                        VISA Debit Card           0
35          Canara Bank                  MasterCard Debit Card           0
36          Canara Bank                    EMV Chip Debit Card           0
43            Axis Bank           Axis Bank Delight Debit Card           0
44            Axis Bank            Axis Bank Value+ Debit Card           0
45            Axis Bank  Axis Bank Titanium Rewards Debit Card           0
46            Axis Bank          Axis Bank Platinum Debit Card           0
55            HDFC Bank                       Classic Platinum           0
56            HDFC Bank                         Platinum Debit           0
57            HDFC Bank                     Preferred Platinum           0
61            HDFC Bank                          Vishesh Debit           0
63         Federal Bank                           Visa Celesta           0
64         Federal Bank                           Visa Imperio           0
65         Federal Bank                            Visa Signet           0
66         Federal Bank                     Mastercard Celesta           0
67         Federal Bank                     Mastercard Imperio           0
68         Federal Bank                      Mastercard Signet           0
69         Federal Bank                           Rupay Signet           0
70         Federal Bank                             Rupay Wave           0
77  Kotak Mahindra Bank            Kotak UPI RuPay Credit Card           0

In [12]:
bank_df["Min_Income_Required"] = pd.to_numeric(
    bank_df["Min_Income_Required"],
    errors="coerce"
)

In [16]:
results = []
for name, income in zip(customer_df["Name"], customer_df["total Income"]):
    eligible = bank_df[bank_df["Min_Income_Required"] <= income]
    results.append({"Customer": name,"Income": income,"Eligible_Cards": ", ".join(eligible["Card_Name"].tolist())})
eligible_df = pd.DataFrame(results)
print(eligible_df)

              Customer  Income  \
0        Ishaan Sharma  151958
1            Dev Desai   46023
2         Aryan Chopra  160608
3        Aditya Kapoor   97435
4         Harsh Chopra  171699
...                ...     ...
1495      Kunal Mishra  190562
1496  Reyansh Malhotra  108985
1497      Aditya Patel  109212
1498      Aditya Joshi   75158
1499         Sai Patel   87098

                                         Eligible_Cards
0     Patanjali RuPay, RuPay Select, SBI Global Inte...
1     RuPay Select, SBI Global International Debit C...
2     Patanjali RuPay, RuPay Select, SBI Global Inte...
3     RuPay Select, SBI Global International Debit C...
4     Patanjali RuPay, RuPay Select, SBI Global Inte...
...                                                 ...
1495  Patanjali RuPay, RuPay Select, SBI Global Inte...
1496  Patanjali RuPay, RuPay Select, SBI Global Inte...
1497  Patanjali RuPay, RuPay Select, SBI Global Inte...
1498  RuPay Select, SBI Global International Debit C...
1499  RuPay Select, SBI Global International Debit C...

[1500 rows x 3 columns]

In [22]:
max_din=bank_df["Dining_Cashback"].max()
best_din=bank_df[bank_df["Dining_Cashback"]==max_gro][["Bank_Name","Card_Name","Dining_Cashback"]]
best_din

    Bank_Name                              Card_Name  Dining_Cashback
38  Axis Bank              Axis Bank Neo Credit Card             10.0
40  Axis Bank           Airtel Axis Bank Credit Card             10.0
45  Axis Bank  Axis Bank Titanium Rewards Debit Card             10.0
47  HDFC Bank                             Milllennia             10.0
48  HDFC Bank                                 Swiggy             10.0
50  HDFC Bank                                Freedom             10.0

In [26]:
bank_df["Benefit"] = bank_df["Total Cashback"] - bank_df["Annual_Fee"]
benefit=bank_df.sort_values("Benefit", ascending=False)[["Bank_Name","Card_Name","Benefit"]]
print(benefit)

         Bank_Name                     Card_Name  Benefit
43       Axis Bank  Axis Bank Delight Debit Card     25.0
28  Bank of Baroda             Prime Credit Card     25.0
0            ICICI     platinum ship credit card     18.5
13             PNB               Patanjali RuPay     13.0
11             PNB                Global Classic     12.0
..             ...                           ...      ...
21             SBI                SBI Card Prime  -2999.0
17           IDBI       IDBI Euphoria World card  -4994.0
22             SBI                SBI Card ELITE  -4999.0
53       HDFC Bank       Diners Club Black Metal  -9988.0
54       HDFC Bank                 Infinia Metal -12485.0

[78 rows x 3 columns]

In [20]:
reward= bank_df.sort_values(by="Rewards Points",ascending=False)[["Bank_Name","Card_Name","Rewards Points"]]
reward

              Bank_Name                     Card_Name  Rewards Points
38            Axis Bank     Axis Bank Neo Credit Card           200.0
3                  IDFC                     Millennia           150.0
13                  PNB               Patanjali RuPay           150.0
9                   PNB               Global Platinum           150.0
12                  PNB                    Millennial           100.0
..                  ...                           ...             ...
40            Axis Bank  Airtel Axis Bank Credit Card             0.0
37            Axis Bank     Axis Bank ACE Credit Card             0.0
14                  PNB                  RuPay Select             0.0
72  Kotak Mahindra Bank   Kotak Cashback+ Credit Card             0.0
76  Kotak Mahindra Bank    PVR INOX Kotak Credit Card             0.0

[78 rows x 3 columns]

In [18]:
lounge= bank_df[bank_df["Lounge access per year"] > 0][["Bank_Name","Card_Name","Lounge access per year"]]
lounge

,Bank_Name,Card_Name,Lounge access per year
2,ICICI,Coral Credit Card,2.0
3,IDFC,Millennia,5.0
4,IDFC,First Classic,6.0
5,IDFC,WOW ! Black,4.0
6,IDFC,First Select,6.0
8,IDFC,Republic Day,4.0
9,PNB,Global Platinum,8.0
10,PNB,Global Gold,2.0
12,PNB,Millennial,2.0
16,IDBI,Royale Signature card,4.0
18,SBI,Cashback SBI Card,4.0
21,SBI,SBI Card Prime,12.0
22,SBI,SBI Card ELITE,14.0
25,SBI,SBI Platinum International Debit Card,4.0
26,Bank of Baroda,HPCL Credit Card,4.0
27,Bank of Baroda,IRCTC Credit Card,4.0
29,Canara Bank,VISA Classic Credit Card,2.0
30,Canara Bank,MasterCard Standard,2.0
31,Canara Bank,RuPay Platinum Credit Card,5.0
32,Canara Bank,Canara Gold Credit Card,5.0
33,Canara Bank,RuPay Debit Card,2.0
34,Canara Bank,VISA Debit Card,2.0
35,Canara Bank,MasterCard Debit Card,2.0
36,Canara Bank,EMV Chip Debit Card,2.0
37,Axis Bank,Axis Bank ACE Credit Card,4.0
40,Axis Bank,Airtel Axis Bank Credit Card,4.0
41,Axis Bank,Flipkart Axis Bank Credit Card,4.0
42,Axis Bank,Axis Bank MyZone Credit Card,4.0
43,Axis Bank,Axis Bank Delight Debit Card,4.0
55,HDFC Bank,Classic Platinum,8.0
56,HDFC Bank,Platinum Debit,8.0
57,HDFC Bank,Preferred Platinum,8.0
58,HDFC Bank,Millennia Debit,4.0
61,HDFC Bank,Vishesh Debit,8.0
62,HDFC Bank,Giga Business,4.0
63,Federal Bank,Visa Celesta,2.0
64,Federal Bank,Visa Imperio,6.0
65,Federal Bank,Visa Signet,2.0
66,Federal Bank,Mastercard Celesta,2.0
67,Federal Bank,Mastercard Imperio,6.0
68,Federal Bank,Mastercard Signet,2.0
69,Federal Bank,Rupay Signet,1.0
70,Federal Bank,Rupay Wave,1.0
74,Kotak Mahindra Bank,Zen Signature Credit Card,2.0
75,Kotak Mahindra Bank,Kotak Air Credit Card,4.0

In [2]:
import pandas as pd

# Load datasets
bank_df = pd.read_csv("bank.csv")
customer_df = pd.read_csv("customer_expense.csv")

# Rename long column names for easier use
bank_df = bank_df.rename(columns={
'Grocery_Cashback(%) [Zepto, BigBasket, etc.]':'grocery_cb',
'Travel_Cashback(%)':'travel_cb',
'Dining_Cashback [Swiggy, Zomato, etc.](%)':'dining_cb',
'Min_Income_Required(Yearly)':'min_income',
'Limit(montly)':'limit',
'Lounge access per year':'lounge',
'Rewards Points':'reward_points'
})

print("===================================")
print("1. Best Credit Card for Grocery")
print("===================================")

grocery_spend = 5000

bank_df["grocery_cashback"] = grocery_spend * bank_df["grocery_cb"]/100
print(bank_df.sort_values("grocery_cashback",ascending=False)[
["Bank_Name","Card_Name","grocery_cashback"]
].head())


print("===================================")
print("2. Cards with No Annual Fee")
print("===================================")

no_fee = bank_df[bank_df["Annual_Fee"] == 0]
print(no_fee[["Bank_Name","Card_Name","Annual_Fee"]])


print("===================================")
print("3. Cards Based on Customer Income")
print("===================================")

customer_income = 500000

eligible_cards = bank_df[bank_df["min_income"] <= customer_income]
print(eligible_cards[["Bank_Name","Card_Name","min_income"]])


print("===================================")
print("4. Total Cashback for Customer")
print("===================================")

grocery = 4000
travel = 2000
dining = 1500

bank_df["total_cashback"] = (
grocery * bank_df["grocery_cb"]/100 +
travel * bank_df["travel_cb"]/100 +
dining * bank_df["dining_cb"]/100
)

print(bank_df[["Bank_Name","Card_Name","total_cashback"]])


print("===================================")
print("5. Best Dining Cashback Cards")
print("===================================")

print(bank_df.sort_values("dining_cb",ascending=False)[
["Bank_Name","Card_Name","dining_cb"]
].head())


print("===================================")
print("6. Annual Fee vs Cashback")
print("===================================")

bank_df["net_value"] = bank_df["total_cashback"] - bank_df["Annual_Fee"]

print(bank_df.sort_values("net_value",ascending=False)[
["Bank_Name","Card_Name","net_value"]
].head())


print("===================================")
print("7. Filter Cards by Monthly Limit")
print("===================================")

required_limit = 50000

limit_cards = bank_df[bank_df["limit"] >= required_limit]
print(limit_cards[["Bank_Name","Card_Name","limit"]])


print("===================================")
print("8. Cards with Highest Reward Points")
print("===================================")

print(bank_df.sort_values("reward_points",ascending=False)[
["Bank_Name","Card_Name","reward_points"]
].head())


print("===================================")
print("9. Cards with Lounge Access")
print("===================================")

lounge_cards = bank_df[bank_df["lounge"] > 0]

print(lounge_cards[["Bank_Name","Card_Name","lounge"]])


print("===================================")
print("10. Credit Card Recommendation")
print("===================================")

income = 500000
grocery = 4000
travel = 2000
dining = 1500

eligible = bank_df[bank_df["min_income"] <= income]

eligible["cashback"] = (
grocery * eligible["grocery_cb"]/100 +
travel * eligible["travel_cb"]/100 +
dining * eligible["dining_cb"]/100
)

eligible["net_benefit"] = eligible["cashback"] - eligible["Annual_Fee"]

recommended = eligible.sort_values("net_benefit",ascending=False)

print(recommended[
["Bank_Name","Card_Name","net_benefit"]
].head(3))

===================================
1. Best Credit Card for Grocery
===================================
         Bank_Name                    Card_Name  grocery_cashback
27  Bank of Baroda            IRCTC Credit Card             500.0
28  Bank of Baroda            Prime Credit Card             500.0
26  Bank of Baroda             HPCL Credit Card             500.0
44       Axis Bank  Axis Bank Value+ Debit Card             250.0
2            ICICI            Coral Credit Card             250.0
===================================
2. Cards with No Annual Fee
===================================
              Bank_Name                              Card_Name  Annual_Fee
0                 ICICI              platinum ship credit card           0
1                 ICICI                  Amazon pay icici card           0
3                  IDFC                              Millennia           0
4                  IDFC                          First Classic           0
6                  IDFC                           First Select           0
8                  IDFC                           Republic Day           0
11                  PNB                         Global Classic           0
13                  PNB                        Patanjali RuPay           0
28       Bank of Baroda                      Prime Credit Card           0
29          Canara Bank               VISA Classic Credit Card           0
30          Canara Bank                    MasterCard Standard           0
31          Canara Bank             RuPay Platinum Credit Card           0
33          Canara Bank                       RuPay Debit Card           0
34          Canara Bank                        VISA Debit Card           0
35          Canara Bank                  MasterCard Debit Card           0
36          Canara Bank                    EMV Chip Debit Card           0
43            Axis Bank           Axis Bank Delight Debit Card           0
44            Axis Bank            Axis Bank Value+ Debit Card           0
45            Axis Bank  Axis Bank Titanium Rewards Debit Card           0
46            Axis Bank          Axis Bank Platinum Debit Card           0
55            HDFC Bank                       Classic Platinum           0
56            HDFC Bank                         Platinum Debit           0
57            HDFC Bank                     Preferred Platinum           0
61            HDFC Bank                          Vishesh Debit           0
63         Federal Bank                           Visa Celesta           0
64         Federal Bank                           Visa Imperio           0
65         Federal Bank                            Visa Signet           0
66         Federal Bank                     Mastercard Celesta           0
67         Federal Bank                     Mastercard Imperio           0
68         Federal Bank                      Mastercard Signet           0
69         Federal Bank                           Rupay Signet           0
70         Federal Bank                             Rupay Wave           0
77  Kotak Mahindra Bank            Kotak UPI RuPay Credit Card           0
===================================
3. Cards Based on Customer Income
===================================

TypeError: '<=' not supported between instances of 'str' and 'int'