In [6]:
import pandas as pd

In [7]:
bank_df=pd.read_csv("bank.csv")
customer_df=pd.read_csv("customer_expense.csv")

In [11]:
bank_df.columns

Index(['Bank_Name', 'Card_Name', 'Annual_Fee', 'Grocery_Cashback',
       'Travel_Cashback', 'Dining_Cashback', 'Min_Income_Required', 'Limit',
       'Grocery Discount', 'Travel_Discount', 'Dining_Discount',
       'Rewards Points', 'Review InPoints', 'CardType',
       'Lounge access per year', 'Total Cashback'],
      dtype='str')

In [32]:
customer_df.columns

Index(['Name', 'Grocery', 'Travelling', 'Electricity', 'Internet', 'EMI',
       'Dining', 'Entertainment', 'OTT', 'Ecommerce', 'UPI_Transactions',
       'total Income'],
      dtype='str')

In [12]:
max_gro=bank_df["Grocery_Cashback"].max()
best_grocery=bank_df[bank_df["Grocery_Cashback"]==max_gro][["Bank_Name","Card_Name","Grocery_Cashback","CardType"]]
best_grocery

         Bank_Name          Card_Name  Grocery_Cashback CardType
26  Bank of Baroda   HPCL Credit Card              10.0   Credit
27  Bank of Baroda  IRCTC Credit Card              10.0   Credit
28  Bank of Baroda  Prime Credit Card              10.0   Credit

In [20]:
no_annual = bank_df[(bank_df["Annual_Fee"] == 0) & (bank_df["CardType"] == "Credit")][["Bank_Name","Card_Name","Annual_Fee"]]
no_annual

              Bank_Name                    Card_Name  Annual_Fee
28       Bank of Baroda            Prime Credit Card           0
29          Canara Bank     VISA Classic Credit Card           0
30          Canara Bank          MasterCard Standard           0
31          Canara Bank   RuPay Platinum Credit Card           0
63         Federal Bank                 Visa Celesta           0
64         Federal Bank                 Visa Imperio           0
65         Federal Bank                  Visa Signet           0
66         Federal Bank           Mastercard Celesta           0
67         Federal Bank           Mastercard Imperio           0
68         Federal Bank            Mastercard Signet           0
69         Federal Bank                 Rupay Signet           0
70         Federal Bank                   Rupay Wave           0
77  Kotak Mahindra Bank  Kotak UPI RuPay Credit Card           0

In [26]:
bank_df["Min_Income_Required"]= bank_df["Min_Income_Required"].str.replace(",","").astype(int)

In [57]:
merged=pd.merge(customer_df,bank_df[bank_df['CardType']=='Credit'],how='cross')
elg=merged[merged['total Income']>=merged['Min_Income_Required']]
elg[['Name','Bank_Name','Card_Name','Min_Income_Required','total Income']]

,Name,Bank_Name,Card_Name,Min_Income_Required,total Income
8,Ishaan Sharma,Bank of Baroda,Prime Credit Card,15000,151958
9,Ishaan Sharma,Canara Bank,VISA Classic Credit Card,150000,151958
10,Ishaan Sharma,Canara Bank,MasterCard Standard,150000,151958
36,Dev Desai,Bank of Baroda,Prime Credit Card,15000,46023
64,Aryan Chopra,Bank of Baroda,Prime Credit Card,15000,160608
...,...,...,...,...,...
41870,Kunal Mishra,Canara Bank,MasterCard Standard,150000,190562
41896,Reyansh Malhotra,Bank of Baroda,Prime Credit Card,15000,108985
41924,Aditya Patel,Bank of Baroda,Prime Credit Card,15000,109212
41952,Aditya Joshi,Bank of Baroda,Prime Credit Card,15000,75158
41980,Sai Patel,Bank of Baroda,Prime Credit Card,15000,87098

In [64]:
merged=pd.merge(customer_df,bank_df[bank_df['CardType']=='Credit'],how='cross')
elg=merged[merged['total Income']>=merged['Min_Income_Required']]
elg['Total_Cashback']=(elg['Travelling']*elg['Travel_Cashback']/100+
elg['Grocery']*elg['Grocery_Cashback']/100+
elg['Dining']*elg['Dining_Cashback']/100)
cashback=elg[elg['Total_Cashback']!=0][['Name','Bank_Name','Card_Name','Total_Cashback']]
cashback

,Name,Bank_Name,Card_Name,Total_Cashback
8,Ishaan Sharma,Bank of Baroda,Prime Credit Card,1094.50
9,Ishaan Sharma,Canara Bank,VISA Classic Credit Card,87.16
10,Ishaan Sharma,Canara Bank,MasterCard Standard,87.16
36,Dev Desai,Bank of Baroda,Prime Credit Card,1284.95
64,Aryan Chopra,Bank of Baroda,Prime Credit Card,3907.90
...,...,...,...,...
41870,Kunal Mishra,Canara Bank,MasterCard Standard,332.36
41896,Reyansh Malhotra,Bank of Baroda,Prime Credit Card,1932.85
41924,Aditya Patel,Bank of Baroda,Prime Credit Card,2355.00
41952,Aditya Joshi,Bank of Baroda,Prime Credit Card,2090.10
41980,Sai Patel,Bank of Baroda,Prime Credit Card,3878.75

In [61]:
max_din=bank_df["Dining_Cashback"].max()
best_din=bank_df[bank_df["Dining_Cashback"]==max_gro][["Bank_Name","Card_Name","Dining_Cashback"]]
best_din

    Bank_Name                              Card_Name  Dining_Cashback
38  Axis Bank              Axis Bank Neo Credit Card             10.0
40  Axis Bank           Airtel Axis Bank Credit Card             10.0
45  Axis Bank  Axis Bank Titanium Rewards Debit Card             10.0
47  HDFC Bank                             Milllennia             10.0
48  HDFC Bank                                 Swiggy             10.0
50  HDFC Bank                                Freedom             10.0

In [67]:
merged=pd.merge(customer_df,bank_df[bank_df['CardType']=='Credit'],how='cross')
elg=merged[merged['total Income']>=merged['Min_Income_Required']]
elg['Total_Cashback']=(elg['Travelling']*elg['Travel_Cashback']/100+
elg['Grocery']*elg['Grocery_Cashback']/100+
elg['Dining']*elg['Dining_Cashback']/100)
elg['benifit']=elg['Total_Cashback']-elg['Annual_Fee']
benifit=elg[['Name','Bank_Name','Card_Name','benifit']]
benifit

                   Name       Bank_Name                 Card_Name  benifit
8         Ishaan Sharma  Bank of Baroda         Prime Credit Card  1094.50
9         Ishaan Sharma     Canara Bank  VISA Classic Credit Card    87.16
10        Ishaan Sharma     Canara Bank       MasterCard Standard    87.16
36            Dev Desai  Bank of Baroda         Prime Credit Card  1284.95
64         Aryan Chopra  Bank of Baroda         Prime Credit Card  3907.90
...                 ...             ...                       ...      ...
41870      Kunal Mishra     Canara Bank       MasterCard Standard   332.36
41896  Reyansh Malhotra  Bank of Baroda         Prime Credit Card  1932.85
41924      Aditya Patel  Bank of Baroda         Prime Credit Card  2355.00
41952      Aditya Joshi  Bank of Baroda         Prime Credit Card  2090.10
41980         Sai Patel  Bank of Baroda         Prime Credit Card  3878.75

[2312 rows x 4 columns]

In [77]:
bank_df["Limit"]= bank_df["Limit"].str.replace(',','').astype(int)

In [82]:
customer_df['Monthly_Spend']=(customer_df['Grocery']+customer_df['Travelling']+customer_df['Dining']+customer_df['Electricity']
+customer_df['Internet']+customer_df['Entertainment']+customer_df['EMI']+customer_df['OTT']
+customer_df['Ecommerce']+customer_df['UPI_Transactions'])
merged=pd.merge(customer_df,bank_df[bank_df['CardType']=='Credit'],how='cross')
elg=merged[merged['total Income']>=merged['Min_Income_Required']]
suitable=elg[elg['Limit']>=elg['Monthly_Spend']][['Name','Bank_Name','Card_Name','Limit','monthly_spend']]
suitable

,Name,Bank_Name,Card_Name,Limit,monthly_spend
8,Ishaan Sharma,Bank of Baroda,Prime Credit Card,100000,41237
36,Dev Desai,Bank of Baroda,Prime Credit Card,100000,44789
64,Aryan Chopra,Bank of Baroda,Prime Credit Card,100000,75433
92,Aditya Kapoor,Bank of Baroda,Prime Credit Card,100000,45772
120,Harsh Chopra,Bank of Baroda,Prime Credit Card,100000,62747
...,...,...,...,...,...
41840,Arjun Kapoor,Bank of Baroda,Prime Credit Card,100000,69956
41868,Kunal Mishra,Bank of Baroda,Prime Credit Card,100000,88347
41896,Reyansh Malhotra,Bank of Baroda,Prime Credit Card,100000,67763
41924,Aditya Patel,Bank of Baroda,Prime Credit Card,100000,51881
41952,Aditya Joshi,Bank of Baroda,Prime Credit Card,100000,59975

In [68]:
reward= bank_df.sort_values(by="Rewards Points",ascending=False)[["Bank_Name","Card_Name","Rewards Points"]]
reward

              Bank_Name                     Card_Name  Rewards Points
38            Axis Bank     Axis Bank Neo Credit Card           200.0
3                  IDFC                     Millennia           150.0
13                  PNB               Patanjali RuPay           150.0
9                   PNB               Global Platinum           150.0
12                  PNB                    Millennial           100.0
..                  ...                           ...             ...
40            Axis Bank  Airtel Axis Bank Credit Card             0.0
37            Axis Bank     Axis Bank ACE Credit Card             0.0
14                  PNB                  RuPay Select             0.0
72  Kotak Mahindra Bank   Kotak Cashback+ Credit Card             0.0
76  Kotak Mahindra Bank    PVR INOX Kotak Credit Card             0.0

[78 rows x 3 columns]

In [69]:
lounge= bank_df[bank_df["Lounge access per year"] > 0][["Bank_Name","Card_Name","Lounge access per year"]]
lounge

,Bank_Name,Card_Name,Lounge access per year
2,ICICI,Coral Credit Card,2.0
3,IDFC,Millennia,5.0
4,IDFC,First Classic,6.0
5,IDFC,WOW ! Black,4.0
6,IDFC,First Select,6.0
8,IDFC,Republic Day,4.0
9,PNB,Global Platinum,8.0
10,PNB,Global Gold,2.0
12,PNB,Millennial,2.0
16,IDBI,Royale Signature card,4.0
18,SBI,Cashback SBI Card,4.0
21,SBI,SBI Card Prime,12.0
22,SBI,SBI Card ELITE,14.0
25,SBI,SBI Platinum International Debit Card,4.0
26,Bank of Baroda,HPCL Credit Card,4.0
27,Bank of Baroda,IRCTC Credit Card,4.0
29,Canara Bank,VISA Classic Credit Card,2.0
30,Canara Bank,MasterCard Standard,2.0
31,Canara Bank,RuPay Platinum Credit Card,5.0
32,Canara Bank,Canara Gold Credit Card,5.0
33,Canara Bank,RuPay Debit Card,2.0
34,Canara Bank,VISA Debit Card,2.0
35,Canara Bank,MasterCard Debit Card,2.0
36,Canara Bank,EMV Chip Debit Card,2.0
37,Axis Bank,Axis Bank ACE Credit Card,4.0
40,Axis Bank,Airtel Axis Bank Credit Card,4.0
41,Axis Bank,Flipkart Axis Bank Credit Card,4.0
42,Axis Bank,Axis Bank MyZone Credit Card,4.0
43,Axis Bank,Axis Bank Delight Debit Card,4.0
55,HDFC Bank,Classic Platinum,8.0
56,HDFC Bank,Platinum Debit,8.0
57,HDFC Bank,Preferred Platinum,8.0
58,HDFC Bank,Millennia Debit,4.0
61,HDFC Bank,Vishesh Debit,8.0
62,HDFC Bank,Giga Business,4.0
63,Federal Bank,Visa Celesta,2.0
64,Federal Bank,Visa Imperio,6.0
65,Federal Bank,Visa Signet,2.0
66,Federal Bank,Mastercard Celesta,2.0
67,Federal Bank,Mastercard Imperio,6.0
68,Federal Bank,Mastercard Signet,2.0
69,Federal Bank,Rupay Signet,1.0
70,Federal Bank,Rupay Wave,1.0
74,Kotak Mahindra Bank,Zen Signature Credit Card,2.0
75,Kotak Mahindra Bank,Kotak Air Credit Card,4.0